version: "3.9"

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3.9
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  cc_pizza_girl:
    build: .
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - rabbitmq
      - redis

volumes:
  redis_data:
  rabbitmq_data:
